/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scheduletab;

/**
 *
 * @author Michael
 */
public enum ScheduleTabPropertyType {
    SCHEDULE_TAB_CALENDAR_LABEL,
    SCHEDULE_TAB_STARTING_LABEL,
    SCHEDULE_TAB_ENDING_LABEL,
    SCHEDULE_TAB_SCHEDULE_LABEL,
    SCHEDULE_TAB_ADD_LABEL,
    SCHEDULE_TAB_TYPE_LABEL,
    SCHEDULE_TAB_DATE_LABEL,
    SCHEDULE_TAB_TITLE_LABEL,
    SCHEDULE_TAB_TOPIC_LABEL,
    SCHEDULE_TAB_LINK_LABEL,
    SCHEDULE_TAB_MINUS_BUTTON,
    SCHEDULE_TAB_TYPE_COLUMN,
    SCHEDULE_TAB_DATE_COLUMN,
    SCHEDULE_TAB_TITLE_COLUMN,
    SCHEDULE_TAB_TOPIC_COLUMN,
    SCHEDULE_TAB_ADD_BUTTON,
    SCHEDULE_TAB_CLEAR_BUTTON,
    SCHEDULE_NULL,
    SCHEDULE_TAB_TITLE_TEXT_AREA,
    SCHEDULE_TAB_TOPIC_TEXT_AREA,
    SCHEDULE_TAB_LINK_TEXT_AREA
}
