/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meetingtimestab;

/**
 *
 * @author Michael
 */
public enum MeetingTimesTabPropertyType {
    MEETING_TIMES_TAB_LECTURES_LABEL,
    MEETING_TIMES_TAB_RECITATIONS_LABEL,
    MEETING_TIMES_TAB_LABS_LABEL,
    MEETING_TIMES_TAB_PLUS_BUTTON1,
    MEETING_TIMES_TAB_PLUS_BUTTON2,
    MEETING_TIMES_TAB_PLUS_BUTTON3,
    MEETING_TIMES_TAB_MINUS_BUTTON1,
    MEETING_TIMES_TAB_MINUS_BUTTON2,
    MEETING_TIMES_TAB_MINUS_BUTTON3,
    MEETING_TIMES_TAB_LECTURES_TABLE_VIEW,
    MEETING_TIMES_TAB_LECTURES_SECTION_COLUMN,
    MEETING_TIMES_TAB_LECTURES_DAYS_COLUMN,
    MEETING_TIMES_TAB_LECTURES_TIME_COLUMN,
    MEETING_TIMES_TAB_LECTURES_ROOM_COLUMN,
    MEETING_TIMES_TAB_RECITATIONS_TABLE_VIEW,
    MEETING_TIMES_TAB_RECITATIONS_SECTION_COLUMN,
    MEETING_TIMES_TAB_RECITATIONS_DAY_TIME_COLUMN,
    MEETING_TIMES_TAB_RECITATIONS_ROOM_COLUMN,
    MEETING_TIMES_TAB_RECITATIONS_TA1_COLUMN,
    MEETING_TIMES_TAB_RECITATIONS_TA2_COLUMN,
    MEETING_TIMES_TAB_LABS_TABLE_VIEW,
    MEETING_TIMES_TAB_LABS_SECTION_COLUMN,
    MEETING_TIMES_TAB_LABS_DAY_TIME_COLUMN,
    MEETING_TIMES_TAB_LABS_ROOM_COLUMN,
    MEETING_TIMES_TAB_LABS_TA1_COLUMN,
    MEETING_TIMES_TAB_LABS_TA2_COLUMN,
}
