/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package syllabusTab;

/**
 *
 * @author Michael
 */
public enum SyllabusTabPropertyType {
    SYLLABUS_TAB_DESCRIPTION_LABEL,
    SYLLABUS_TAB_TOPICS_LABEL,
    SYLLABUS_TAB_PREREQUISITES_LABEL,
    SYLLABUS_TAB_OUTCOMES_LABEL,
    SYLLABUS_TAB_TEXTBOOKS_LABEL,
    SYLLABUS_TAB_GRADED_COMPONENTS_LABEL,
    SYLLABUS_TAB_GRADING_NOTE_LABEL,
    SYLLABUS_TAB_ACADEMIC_DISHONESTY_LABEL,
    SYLLABUS_TAB_SPECIAL_ASSISTANCE_LABEL,
    SYLLABUS_TAB_DESCRIPTION_PLUS_BUTTON,
    SYLLABUS_TAB_TOPICS_PLUS_BUTTON,
    SYLLABUS_TAB_PREREQUISITES_PLUS_BUTTON,
    SYLLABUS_TAB_OUTCOMES_PLUS_BUTTON,
    SYLLABUS_TAB_TEXTBOOKS_PLUS_BUTTON,
    SYLLABUS_TAB_GRADED_COMPONENTS_PLUS_BUTTON,
    SYLLABUS_TAB_GRADED_NOTE_PLUS_BUTTON,
    SYLLABUS_TAB_ACADEMIC_DISHONESTY_PLUS_BUTTON,
    SYLLABUS_TAB_SPECIAL_ASSISTANCE_PLUS_BUTTON,
    SYLLABUS_TAB_DESCRIPTION_TEXT_AREA,
    SYLLABUS_TAB_TOPICS_TEXT_AREA,
    SYLLABUS_TAB_PREREQUISITES_TEXT_AREA,
    SYLLABUS_TAB_OUTCOMES_TEXT_AREA,
    SYLLABUS_TAB_TEXTBOOKS_TEXT_AREA,
    SYLLABUS_TAB_GRADED_COMPONENTS_TEXT_AREA,
    SYLLABUS_TAB_GRADED_NOTE_TEXT_AREA,
    SYLLABUS_TAB_ACADEMIC_DISHONESTY_TEXT_AREA,
    SYLLABUS_TAB_SPECIAL_ASSISTANCE_TEXT_AREA,
}
