/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package syllabustab;

/**
 *
 * @author Michael
 */
public enum SyllabusTabPropertyType {
    SYLLABUS_TAB_DESCRIPTION_LABEL,
    SYLLABUS_TAB_TOPICS_LABEL,
    SYLLABUS_TAB_PREREQUISITES_LABEL,
    SYLLABUS_TAB_OUTCOMES_LABEL,
    SYLLABUS_TAB_TEXTBOOKS_LABEL,
    SYLLABUS_TAB_GRADED_COMPONENTS_LABEL,
    SYLLABUS_TAB_GRADING_NOTE_LABEL,
    SYLLABUS_TAB_ACADEMIC_DISHONESTY_LABEL,
    SYLLABUS_TAB_SPECIAL_ASSISTANCE_LABEL,
    SYLLABUS_TAB_PLUS_BUTTON1,
    SYLLABUS_TAB_PLUS_BUTTON2,
    SYLLABUS_TAB_PLUS_BUTTON3,
    SYLLABUS_TAB_PLUS_BUTTON4,
    SYLLABUS_TAB_PLUS_BUTTON5,
    SYLLABUS_TAB_PLUS_BUTTON6,
    SYLLABUS_TAB_PLUS_BUTTON7,
    SYLLABUS_TAB_PLUS_BUTTON8,
    SYLLABUS_TAB_PLUS_BUTTON9,
}
